name: Workflow for Internal PRs with Unit & Integration Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sha:
        description: "Git commit SHA to test (leave empty to use current commit)"
        required: false
        type: string

jobs:
  Timestamp:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch' }}
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-timestamp.yml@main

  tests:
    needs: [Timestamp]
    uses: ./.github/workflows/build-test-workflow.yml
    with:
      sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || (github.event_name == 'workflow_dispatch' && inputs.sha) || github.sha }}
      ENVIRONMENT: "aeneid"
    secrets:
      WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
      WALLET_ADDRESS_2: ${{ secrets.WALLET_ADDRESS_2 }}
      WALLET_PRIVATE_KEY_2: ${{ secrets.WALLET_PRIVATE_KEY_2 }}
      RPC_PROVIDER_URL: ${{ secrets.RPC_PROVIDER_URL }}
